// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Program = 1,
  Comment = 2,
  Keyword = 3,
  ControlFlowKeyword = 4,
  Bool = 5,
  Null = 6,
  Number = 7,
  String = 8,
  TypeName = 9,
  FunctionName = 10,
  Identifier = 11
