// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {jsonHighlighting} from "./highlight"
export const parser = LRParser.deserialize({
  version: 14,
  states: "bOVQPOOOOQO'#Cj'#CjQOQPOO",
  stateData: "t~O]OS~OQPORPOSPOTPOUPOVPOWPOXPOYPO~O",
  goto: "c_PPPPPPPPPPPPPP`RQO",
  nodeNames: "⚠ Program Comment Keyword ControlFlowKeyword Bool Null Number String TypeName Identifier",
  maxTerm: 14,
  propSources: [jsonHighlighting],
  skippedNodes: [0],
  repeatNodeCount: 0,
  tokenData: "3i~RoXY#SYZ#S]^#Spq#Xrs$z}!O%o!P!Q'i!Q!R%x!R!['W!b!c+P!c!},O#R#S,O#T#U,T#U#V,O#V#W-W#W#X,O#X#Y-r#Y#Z.]#Z#],O#]#^/V#^#b,O#b#c/_#c#d/x#d#e0v#e#f,O#f#g2T#g#h,O#h#i2u#i#k,O#k#l3T#l#o,O~#XO]~~#^R]~#Y#Z#g#]#^$U#g#h$[~#jP#`#a#m~#pP#c#d#s~#vP#T#U#y~#|P#h#i$P~$UOX~~$XP#b#c#y~$_P#h#i$b~$eP#f#g$h~$kP#]#^$n~$qP#b#c$t~$wP#Z#[$P~$}Vpq$zqr$zrs%ds#O$z#P;'S$z;'S;=`%i<%lO$z~%iOW~~%lP;=`<%l$z~%rQ!Q!R%x!R!['W~%}RV~!O!P&W!g!h&l#X#Y&l~&ZP!Q![&^~&cRV~!Q![&^!g!h&l#X#Y&l~&oR{|&x}!O&x!Q!['O~&{P!Q!['O~'TPV~!Q!['O~']SV~!O!P&W!Q!['W!g!h&l#X#Y&l~'lQz{'r!P!Q*b~'uZXY'rYZ'r]^'rpq'rqr'rsz'rz{(h{#O'r#P;'S'r;'S;=`*[<%lO'r~(k]XY'rYZ'r]^'rpq'rqr'rsz'rz{(h{!P'r!P!Q)d!Q#O'r#P;'S'r;'S;=`*[<%lO'r~)iZQ~XY'rYZ'r]^'rpq'rqr'rsz'rz{(h{#O'r#P;'S'r;'S;=`*[<%lO'r~*_P;=`<%l'r~*gUQ~pq*bqr*bs#O*b#P;'S*b;'S;=`*y<%lO*b~*|P;=`<%l*b~+SPrs+V~+YYXY+VYZ+V]^+Vpq+Vqr+Vrs%ds#O+V#P;'S+V;'S;=`+x<%lO+V~+{P;=`<%l+V~,TOY~~,YPY~#U#V,]~,`P#g#h,c~,fP#h#i,i~,lP#f#g,o~,rP#T#U,u~,xP#V#W,{~-OP#h#i-R~-WOR~~-]PY~#`#a-`~-cP#T#U-f~-iP#g#h-l~-oP#g#h-R~-wPY~#`#a-z~-}P#g#h.Q~.TP#X#Y.W~.]OS~~.bQY~#T#U.h#c#d/P~.kP#`#a.n~.qP#g#h.t~.wP#X#Y.z~/POT~~/SP#f#g.W~/[PY~#Y#Z.W~/dPY~#i#j/g~/jP#`#a/m~/pP#`#a/s~/xOU~~/}PY~#j#k0Q~0TP#X#Y0W~0ZP#f#g0^~0aP#f#g0d~0gP#]#^0j~0mP#W#X0p~0sP#X#Y-R~0{QY~#f#g1R#i#j1k~1UP#]#^1X~1[P#j#k1_~1bP#T#U1e~1hP#h#i0p~1nP#U#V1q~1tP#`#a1w~1zP#]#^1}~2QP#V#W-R~2YPY~#X#Y2]~2`P#h#i2c~2fP#i#j2i~2lP#f#g2o~2rP#b#c.W~2zPY~#f#g2}~3QP#i#j.t~3YPY~#[#]3]~3`P#]#^3c~3fP#`#a.Q",
  tokenizers: [0],
  topRules: {"Program":[0,1]},
  tokenPrec: 0
})
