// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {jsonHighlighting} from "./highlight"
export const parser = LRParser.deserialize({
  version: 14,
  states: "bOVQPOOOOQO'#Ck'#CkQOQPOO",
  stateData: "w~O^OS~OQPORPOSPOTPOUPOVPOWPOXPOYPOZPO~O",
  goto: "d`PPPPPPPPPPPPPPPaRQO",
  nodeNames: "⚠ Program Comment Keyword ControlFlowKeyword Bool Null Number String TypeName FunctionName Identifier",
  maxTerm: 15,
  propSources: [jsonHighlighting],
  skippedNodes: [0],
  repeatNodeCount: 0,
  tokenData: "9f~RkXY!vYZ!v]^!vpq!{rs$[}!O%P!P!Q&y!Q!R%Y!R![&h!b!c*a!c!d+`!g!h+l!i!j,s!n!o-o!v!w.R#T#U0b#V#W1c#X#Y1{#Y#Z2d#]#^3v#b#c4P#c#d4q#d#e5m#f#g6x#g#h7h#h#i8a#k#l9S~!{O^~~#QP^~!v!w#T~#WP#c#d#Z~#^P#_#`#a~#dP#X#Y#g~#jP#b#c#m~#pP#]#^#s~#vP#n#o#y~#|P#X#Y$P~$SPxy$V~$[OY~~$_Vpq$[qr$[rs$ts#O$[#P;'S$[;'S;=`$y<%lO$[~$yOW~~$|P;=`<%l$[~%SQ!Q!R%Y!R![&h~%_RV~!O!P%h!g!h%|#X#Y%|~%kP!Q![%n~%sRV~!Q![%n!g!h%|#X#Y%|~&PR{|&Y}!O&Y!Q![&`~&]P!Q![&`~&ePV~!Q![&`~&mSV~!O!P%h!Q![&h!g!h%|#X#Y%|~&|Qz{'S!P!Q)r~'VZXY'SYZ'S]^'Spq'Sqr'Ssz'Sz{'x{#O'S#P;'S'S;'S;=`)l<%lO'S~'{]XY'SYZ'S]^'Spq'Sqr'Ssz'Sz{'x{!P'S!P!Q(t!Q#O'S#P;'S'S;'S;=`)l<%lO'S~(yZQ~XY'SYZ'S]^'Spq'Sqr'Ssz'Sz{'x{#O'S#P;'S'S;'S;=`)l<%lO'S~)oP;=`<%l'S~)wUQ~pq)rqr)rs#O)r#P;'S)r;'S;=`*Z<%lO)r~*^P;=`<%l)r~*dPrs*g~*jYXY*gYZ*g]^*gpq*gqr*grs$ts#O*g#P;'S*g;'S;=`+Y<%lO*g~+]P;=`<%l*g~+cP#W#X+f~+iP#W#X$V~+oP#l#m+r~+uP#V#W+x~+{P#X#Y,O~,RP#d#e,U~,XP#h#i,[~,_P#]#^,b~,eP#c#d,h~,kP#b#c,n~,sOZ~~,vP#X#Y,y~,|P#b#c-P~-SP#X#Y-V~-YP#f#g-]~-`P#T#U-c~-fP#h#i-i~-lP#X#Y$V~-rP#]#^-u~-xP#g#h-{~.OP#h#i,n~.UQ#c#d.[#f#g0U~._P#_#`.b~.eP#X#Y.h~.kP#b#c.n~.sQZ~#R#S.y#]#^/c~.|P!r!s/P~/SP#f#g/V~/YP#]#^/]~/`P#b#c-{~/fP#n#o/i~/lP#X#Y/o~/rQ!n!o/x#f#g,n~/{P#]#^0O~0RP#b#c-i~0XP#]#^0[~0_P#a#b$V~0eP#U#V0h~0kP#g#h0n~0qP#h#i0t~0wP#f#g0z~0}P#T#U1Q~1TP#V#W1W~1ZP#h#i1^~1cOR~~1fP#`#a1i~1lP#T#U1o~1rP#g#h1u~1xP#g#h1^~2OP#`#a2R~2UP#g#h2X~2[P#X#Y2_~2dOS~~2gR#T#U2p#`#a3X#c#d3p~2sP#`#a2v~2yP#g#h2|~3PP#X#Y3S~3XOT~~3[P#c#d3_~3bP#T#U3e~3hP#h#i3k~3pOX~~3sP#f#g2_~3yQ#Y#Z2_#b#c3e~4SQ#X#Y4Y#i#j4`~4]P#k#l1^~4cP#`#a4f~4iP#`#a4l~4qOU~~4tP#j#k4w~4zP#X#Y4}~5QP#f#g5T~5WP#f#g5Z~5^P#]#^5a~5dP#W#X5g~5jP#X#Y1^~5pQ#f#g5v#i#j6`~5yP#]#^5|~6PP#j#k6S~6VP#T#U6Y~6]P#h#i5g~6cP#U#V6f~6iP#`#a6l~6oP#]#^6r~6uP#V#W1^~6{P#X#Y7O~7RP#h#i7U~7XP#i#j7[~7_P#f#g7b~7eP#b#c2_~7kP#h#i7n~7qQ#T#U7w#f#g7}~7zP#h#i6l~8QP#]#^8T~8WP#b#c8Z~8^P#Z#[3k~8dQ#[#]8j#f#g8|~8mP#f#g8p~8sP#c#d8v~8yP#k#l2_~9PP#i#j2|~9VP#[#]9Y~9]P#]#^9`~9cP#`#a2X",
  tokenizers: [0],
  topRules: {"Program":[0,1]},
  tokenPrec: 0
})
