// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  JsonText = 1,
  Comment = 2,
  Keyword = 3,
  ControlFlowKeyword = 4,
  True = 5,
  False = 6,
  Null = 7,
  Number = 8,
  String = 9,
  TypeName = 10,
  Identifier = 11
