// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Program = 1,
  Comment = 2,
  Keyword = 3,
  ControlFlowKeyword = 4,
  Number = 5,
  String = 6,
  Register = 7,
  TypeName = 8
