// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {jsonHighlighting} from "./highlight"
export const parser = LRParser.deserialize({
  version: 14,
  states: "bOQOPOOOOOO'#Cf'#CfQOOOOO",
  stateData: "i~OQPORPOSPOTPOUPOVPOWPO~O",
  goto: "_ZPPPPPPPPPP[RQO",
  nodeNames: "⚠ Program Comment Keyword ControlFlowKeyword Number String Register TypeName",
  maxTerm: 10,
  propSources: [jsonHighlighting],
  skippedNodes: [0],
  repeatNodeCount: 0,
  tokenData: "5{~Rgrs!j}!O#_!Q!R#h!R![$v![!]%X!]!^%^!b!c%{!c!}&R#R#S&R#T#V&R#V#W&b#W#X(R#X#Y)P#Y#Z&R#Z#[+Y#[#a&R#a#b-{#b#f&R#f#g.w#g#h0S#h#l&R#l#m5P#m#o&R~!mVpq!jqr!jrs#Ss#O!j#P;'S!j;'S;=`#X<%lO!j~#XOU~~#[P;=`<%l!j~#bQ!Q!R#h!R![$v~#mRT~!O!P#v!g!h$[#X#Y$[~#yP!Q![#|~$RRT~!Q![#|!g!h$[#X#Y$[~$_R{|$h}!O$h!Q![$n~$kP!Q![$n~$sPT~!Q![$n~${ST~!O!P#v!Q![$v!g!h$[#X#Y$[~%^OS~~%cUQ~pq%^qr%^s#O%^#P;'S%^;'S;=`%u<%lO%^~%xP;=`<%l%^~&OPrs!j~&US![!]%X!c!}&R#R#S&R#T#o&R~&eT![!]%X!c!}&R#R#S&R#T#U&t#U#o&R~&wU![!]%X!c!}&R#R#S&R#T#`&R#`#a'Z#a#o&R~'^U![!]%X!c!}&R#R#S&R#T#`&R#`#a'p#a#o&R~'uSS~![!]%X!c!}&R#R#S&R#T#o&R~(UU![!]%X!c!}&R#R#S&R#T#U&R#U#V(h#V#o&R~(kTpq(z![!]%X!c!}&R#R#S&R#T#o&R~)POW~~)SY![!]%X!c!}&R#R#S&R#T#U)r#U#V)r#V#W)r#W#X)r#X#g&R#g#h)r#h#o&R~)u[![!]%X!c!}&R#R#S&R#T#W&R#W#X*k#X#]&R#]#^*k#^#`&R#`#a*k#a#l&R#l#m*k#m#o&R~*nVYZ+Tpq+T|}+T![!]%X!c!}&R#R#S&R#T#o&R~+YOV~~+]U![!]%X!c!}&R#R#S&R#T#`&R#`#a+o#a#o&R~+rU![!]%X!c!}&R#R#S&R#T#c&R#c#d,U#d#o&R~,XU![!]%X!c!}&R#R#S&R#T#U&R#U#V,k#V#o&R~,nT![!]%X!c!}&R#R#S&R#T#U,}#U#o&R~-QU![!]%X!c!}&R#R#S&R#T#`&R#`#a-d#a#o&R~-gTpq-v![!]%X!c!}&R#R#S&R#T#o&R~-{OR~~.OU![!]%X!c!}&R#R#S&R#T#c&R#c#d.b#d#o&R~.eU![!]%X!c!}&R#R#S&R#T#j&R#j#k-d#k#o&R~.zZ![!]%X!c!}&R#R#S&R#T#U)r#U#V)r#V#W)r#W#X)r#X#Y/m#Y#g&R#g#h)r#h#o&R~/pU![!]%X!c!}&R#R#S&R#T#h&R#h#i'p#i#o&R~0VW![!]%X!c!}&R#R#S&R#T#X&R#X#Y0o#Y#m&R#m#n4T#n#o&R~0rU![!]%X!c!}&R#R#S&R#T#V&R#V#W1U#W#o&R~1XU![!]%X!c!}&R#R#S&R#T#h&R#h#i1k#i#o&R~1nU![!]%X!c!}&R#R#S&R#T#]&R#]#^2Q#^#o&R~2TU![!]%X!c!}&R#R#S&R#T#c&R#c#d2g#d#o&R~2jU![!]%X!c!}&R#R#S&R#T#b&R#b#c2|#c#o&R~3PTpq3`![!]%X!c!}&R#R#S&R#T#o&R~3cP!O!P3f~3kUS~pq3fqr3fs#O3f#P;'S3f;'S;=`3}<%lO3f~4QP;=`<%l3f~4WU![!]%X!c!}&R#R#S&R#T#g&R#g#h4j#h#o&R~4mU![!]%X!c!}&R#R#S&R#T#V&R#V#W&b#W#o&R~5SU![!]%X!c!}&R#R#S&R#T#c&R#c#d5f#d#o&R~5iU![!]%X!c!}&R#R#S&R#T#f&R#f#g-d#g#o&R",
  tokenizers: [0],
  topRules: {"Program":[0,1]},
  tokenPrec: 0
})
